parameters:
  instagram.subscription.token: RamirezPortfolio1984
  instagram.redirect_route_login: instagram_check
  instagram.redirect_route_logout: instagram_thanks

  instaphp.config:
    version: v1
    log_path: %kernel.logs_dir%/instagram-%kernel.environment%.log
    endpoint: https://api.instagram.com
    client_id: %instagram_api_client_id%
    client_secret: %instagram_api_client_secret%
    scope: comments+likes+relationships
    oauth_path: /oauth/authorize/?client_id={client_id}&amp;response_type=code&amp;redirect_uri={redirect_uri}
    oauth_token_path: /oauth/access_token/
    redirect_route: instagram_callback
    no_verify_peer: true

services:
    instagram:
        class:            InstagramBundle\Adapter\InstagramAdapter
        arguments:        [%instaphp.config%, @router]