main_page_blog:
    resource: "@MainPageBlogBundle/Resources/config/routing.yml"
    prefix:   /

main_entity:
    resource: "@MainEntityBundle/Resources/config/routing.yml"
    prefix:   /

main_page_frontend:
    resource: "@MainPageFrontendBundle/Resources/config/routing.yml"
    prefix:   /

