main_page_backend:
    resource: "@MainPageBackendBundle/Resources/config/routing.yml"
    prefix:   /s/a

main_page_blog:
    resource: "@MainPageBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

main_entity:
    resource: "@MainEntityBundle/Resources/config/routing.yml"
    prefix:   /

main_page_frontend:
    resource: "@MainPageFrontendBundle/Resources/config/routing.yml"
    prefix:   /

# HWI OAUTH
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
google_login:
    pattern: /login/check-google
    
logout:
    path:   /logout
