security:
    acl:
        connection: default
    encoders:
        Main\EntityBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
 
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
 
    providers:
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider
 
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout: true
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: /connect/google
                failure_path: /login
#                success_handler: security_handler
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
 
    access_control:
        - { path: ^/s/a/,    roles: ROLE_SUPER_ADMIN }
        - { path: ^/s/,      roles: ROLE_ADMIN }
        - { path: ^/blog/s/, roles: ROLE_USER }
        - { path: ^/,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,    roles: ROLE_USER }
