homepage:
    path:     /
    defaults: { _controller: MainPageFrontendBundle:Default:index }
game_secure_save:
    path:     /game/s/saveScore
    defaults: { _controller: MainPageFrontendBundle:Default:gameSave }
    methods:  [POST]
game_secure:
    path:     /game/s
    defaults: { _controller: MainPageFrontendBundle:Default:game }
game:
    path:     /game
    defaults: { _controller: MainPageFrontendBundle:Default:game }
google_call_back:
    path:     /oauth2callback
    defaults: { _controller: MainPageFrontendBundle:Default:oauth2callback }
samples_to_do_list:
    path:     /samples/todo-list
    defaults: { _controller: MainPageFrontendBundle:Default:toDoList }
samples_fitrition:
    path:     /samples/fitrition
    defaults: { _controller: MainPageFrontendBundle:Default:fitrition }
samples_symbiosis:
    path:     /samples/symbiosis
    defaults: { _controller: MainPageFrontendBundle:Default:symbiosis }
webhooks:
    path:     /webhooks
    defaults: { _controller: MainPageFrontendBundle:Default:webhooks }
api:
    path:     /api-callback
    defaults: { _controller: MainPageFrontendBundle:Default:apiCallback }

blog:
    path:     /blog
    defaults: { _controller: MainPageFrontendBundle:Blog:index }  
    
personal:
    path:     /personal-branding
    defaults: { _controller: MainPageFrontendBundle:Default:personalBranding }