services:
#    main_page_frontend.example:
#        class: Main\Page\FrontendBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  frontend.git.mail.event:
    class: Main\Page\FrontendBundle\EventListener\GitMailListener
    arguments: ["@mailer", "@logger","@templating"]
    tags:
      - { name: kernel.event_listener, event: git.mail.event, method: onGitMailEvent }
