services:
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    ib_user.oauth_user_provider:
        class: Main\EntityBundle\Auth\OAuthProvider
        arguments: [@session, @doctrine, @service_container]
    security_handler:
        class: Main\EntityBundle\Handler\SecurityHandler
        arguments:  [@router]
